nelmio_api_doc:
    documentation:
        info:
            title: Gestion de CV Wilfried Fournier
            description: Permet de gérer les catégories et compétences. 
            version: 1.0.0
    areas: # to filter documented areas        
        default:
            path_patterns: [ ^/categories , ^/skills ]
